#类不能使用帕斯卡命名或者驼峰命名,若不用，则不设置相应的结构体，自然不会读取

secret: token111

api: 0.0.0.0:44444

mysql:
    dbAddress: [ 47.112.160.66:3306, 127.0.0.1:3306 ]
    dbUserName: root
    dbPassword: 123456
    dbChatName: eChat
    dbMsgName: eMsg
    dbMsgTableNum: 10
    dbMaxOpenConns: 20
    dbMaxIdleConns: 10
    dbMaxLifeTime: 120


